// <auto-generated />
using CoreWebDemo1.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreWebDemo1.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreWebDemo1.Models.ProductAttrKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AttrName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("EnterType")
                        .HasColumnType("int");

                    b.Property<int>("IsImg")
                        .HasColumnType("int");

                    b.Property<int>("IsSku")
                        .HasColumnType("int");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<int>("ProductCategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductAttrKeys");
                });

            modelBuilder.Entity("CoreWebDemo1.Models.ProductAttrValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AttrValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProductAttrKeyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductAttrValues");
                });

            modelBuilder.Entity("CoreWebDemo1.Models.ProductCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("KeyWords")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<int>("PID")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
